title: "Schulradar Ruhrgebiet"
description: "Schulen im Ruhrgebiet finden und filtern. Alle Privatschulen und Ã¶ffentliche Schulen sind hier zu finden."
url: "http://schulradar-ruhrgebiet.de"
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

exclude:
  - "scripts"
  - "_cities/_city.md.erb"
  - "CNAME"
  - "CONTRIBUTING.md"
  - "Gemfile*"
  - "mission"
  - "README.md"

sass:
  style: :compressed

collections:
  cities:
    output: true
    permalink: /stadt/:path/
